# @package _global_

defaults:
  - override /data: x1_insert_2cam
  - override /model: fastwam
  - _self_

# dataloading
batch_size: 16
num_workers: 8

model:
  mot_checkpoint_mixed_attn: false

# scheduler
lr_scheduler_type: "cosine"
learning_rate: 1e-4
num_epochs: 10
max_steps: null
log_every: 10
save_every: 2000
eval_every: 200

# training
gradient_accumulation_steps: 1
weight_decay: 1e-2
resume: null
